#!/bin/bash -e

echocol() { echo -e "\033[32m*** $@...\033[0m"; }

echocol mkdist
./bin/mkdist

tests="server serverx tar"

for t in $tests; do
	echocol $t
	if [[ $t == serverx ]]; then
		./test/server x
	else
		./test/$t
	fi
done
