#!/bin/bash -e

assert() {
	echo -ne "\033[31m$1...\033[0m "
	if [[ $2 == $3 ]]; then
		echo OK
	else
		echo -e "FAIL:"
		echo "Actual: [$2]"
		echo "Expected: [$3]"
		exit 1
	fi
}

# Prepare the configuration

export TM_SETTINGS=/tmp/tm_server/conf.py

rm -rf /tmp/tm_server
mkdir -p /tmp/tm_server/{tar_dir,untar_dir}
touch /tmp/tm_server/tar_dir/TEST

./bin/tm mkconf -b ./test/conf.py -r ./test/uids.tsv -u /tmp/tm_server/uploads /tmp/tm_server/tar_dir $TM_SETTINGS

# test

assert "Gensecrets" "$(./bin/gensecrets /tmp/tm_server/conf.py)" "$(echo -e '1:49a4405aafe63df05202df08f8f75c9247b7168159c964f697ba6f974ae40588\na:5c39be99362b4e3d7db4d549055134a5ffa6ecae0926f9f7897393bc60fdc9e9\ns:31aa7ab3db1f26dae9daf68f664c242d4c9adbcef36506c134c3eed4573f7bdc\nd:3f4773b5ceb1c8a16db4c98ff5b0b643f38231b798b034dd4067da74a3e8e5a3\n')"

