#!/bin/bash -e

assert() { echo -ne "\033[31m$1...\033[0m "; if [[ $2 == $3 ]]; then echo OK; else echo FAIL, "$2"; exit 1; fi; }

rm -rf /tmp/tm_test
mkdir -p /tmp/tm_test
export TM_SETTINGS=/tmp/tm_test/conf.py

export PYTHONPATH=.

# Prepare the configuration

mkdir /tmp/tm_test/tar_dir
touch /tmp/tm_test/tar_dir/TEST

python -m tm.mkconf $TM_SETTINGS ./test/conf.py /tmp/tm_test/tar_dir ./test/uids.tsv

pg() { python -c "from urllib2 import urlopen; print urlopen( 'http://localhost:8000/$1' ).read()" | python; }

killall python 2>/dev/null || true
if [ -z "$1" ]; then
	python -m tm.web prod > /tmp/tm_test/out 2> /tmp/tm_test/err &
else
	python -m tm.web &
fi
sleep 2


assert "Successful sign (double quote, via bash)" "$(pg d | bash)" "*With \" double*"

assert "Successful idenfity (double quote)" "$(/tmp/tm_test/home/tmclient id)" 'd With " double quote'
assert "Successful sign (quote, match)" "$(pg a)" "*With ' quote*"

assert "Successful sign (full check)" "$(pg 1)" 'echo "Effettuata installazione in /tmp/tm_test/home per: Fròst"; echo "TESTCONF"; echo /tmp/tm_test/home'

rm -f /tmp/tm_test/home/TEST
/tmp/tm_test/home/.tm dl
assert "Download" "$(ls -1 /tmp/tm_test/home/TEST 2>&1)" "/tmp/tm_test/home/TEST"

assert "Repeated sign" "$(pg 1)" 'echo "Matricola già in uso per lo studente: Fròst"'

assert "Not registered" "$(pg x)" "echo \"Matricola non registrata all'esame\""

assert "Upload" "$(/tmp/tm_test/home/.tm ul ^TEST)" "TEST"

assert "Received upload" "$(tar -C /tmp -xvf /tmp/tm_test/uploads/1/*.tar TEST 2>&1)" "TEST"

perl -i -pe 's/49a4405aafe63df05202df08f8f75c9247b7168159c964f697ba6f974ae40588/boo/' /tmp/tm_test/home/.tm
assert "Client auth error" "$(/tmp/tm_test/home/.tm ul ^TEST 2>&1)" "Si è verificato un errore inatteso del cliernt!"

touch /tmp/tm_test/uploads/s
assert "Bootstrap failure" "$(pg s)" 'echo "Si è verificato un errore inatteso di avvio!"'

rm -rf /tmp/tm_test/home /tmp/tm_test/uploads/s
touch /tmp/tm_test/home
assert "Installation failure" "$(pg s 2>&1)" 'Si è verificato un errore inatteso di installazione!'

assert "Auth error" "$(curl -d signature=x -sL http://localhost:8000/)" '# Firma mancante, o invalida!'

assert "Internal error" "$(curl -d signature='s:31aa7ab3db1f26dae9daf68f664c242d4c9adbcef36506c134c3eed4573f7bdc' -d tar='ERROR' -sL http://localhost:8000/)" '# Si è verificato un errore inatteso del server!'

killall python 2>/dev/null
