#!/bin/bash -e

echocol() { echo -ne "\033[31m$@...\033[0m "; }

if [ -d /tmp/tm_tar ]; then
	chmod -R u+rwX /tmp/tm_tar
	rm -rf /tmp/tm_tar
fi

mkdir -p /tmp/tm_tar/base/{one,two}
ln -s one /tmp/tm_tar/base/three
echo one.a > /tmp/tm_tar/base/one/a1
echo one.b > /tmp/tm_tar/base/one/b1
echo two.a > /tmp/tm_tar/base/two/a2
echo two.b > /tmp/tm_tar/base/two/b2
chmod -R u=rX,go= /tmp/tm_tar/base

export PYTHONPATH=tm.zip

echocol "Creation with permissions preservation and date setting to epoch"
localdate=$(python -c 'import time; print "%d-%02d-%02d %02d:%02d:%02d" % time.localtime( 1 )[ :6 ]')
if diff -b \
	<(python -c 'from tm.mkconf import tar, lstar; lstar( tar( "/tmp/tm_tar/base", verbose = False ) )' |  awk '{print $1, $4, $5, $6}' | sort) \
	<(cat <<EOF
-r-------- $localdate one/a1
-r-------- $localdate one/b1
-r-------- $localdate three/a1
-r-------- $localdate three/b1
-r-------- $localdate two/a2
-r-------- $localdate two/b2
-r-x------ $localdate one/
-r-x------ $localdate three/
-r-x------ $localdate two/
EOF
); then
	echo OK
else
	echo FAIL
	exit 1
fi

echocol "Extraction and dereferencing"
python -c 'from tm.mkconf import tar, untar; untar( tar( "/tmp/tm_tar/base", verbose = False ), "/tmp/tm_tar/extract" )'
if [ -h /tmp/tm_tar/extract/three ]; then
	echo FAIL
	exit 1
else
	echo OK
fi

echocol "Re-extraction"
if python -c 'from tm.mkconf import tar, untar; untar( tar( "/tmp/tm_tar/base", verbose = False ), "/tmp/tm_tar/extract" )'; then
	echo OK
else
	echo FAIL
	exit 1
fi

echocol "Re-extraction after setting perms to 0000"
find /tmp/tm_tar/extract -depth -exec chmod a= {} \;
python -c 'from tm.mkconf import tar, untar; untar( tar( "/tmp/tm_tar/base", verbose = False ), "/tmp/tm_tar/extract" )'
if diff -b <( find /tmp/tm_tar/extract | sort ) <( cat <<EOF
/tmp/tm_tar/extract
/tmp/tm_tar/extract/one
/tmp/tm_tar/extract/one/a1
/tmp/tm_tar/extract/one/b1
/tmp/tm_tar/extract/three
/tmp/tm_tar/extract/three/a1
/tmp/tm_tar/extract/three/b1
/tmp/tm_tar/extract/two
/tmp/tm_tar/extract/two/a2
/tmp/tm_tar/extract/two/b2
EOF
); then
	echo OK
else
	echo FAIL
	exit 1
fi

echocol "Re-extraction after messing up with content and files"
find /tmp/tm_tar/extract -depth -exec chmod u+rwX {} \;
echo mess.a > /tmp/tm_tar/extract/one/a1
echo mess.b > /tmp/tm_tar/extract/two/b2
rm /tmp/tm_tar/extract/three/a1
python -c 'from tm.mkconf import tar, untar; untar( tar( "/tmp/tm_tar/base", verbose = False ), "/tmp/tm_tar/extract" )'
if diff -qr /tmp/tm_tar/extract /tmp/tm_tar/base; then
	echo OK
else
	echo FAIL
	exit 1
fi
